version: "3.7"
services:
  web:
    image: nginx:latest
    restart: always
    container_name: web
    ports:
      - "${PUBLIC_WEB_PORT}"
    volumes:
      - ./app:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - "${SHARED}"

  php:
    build: ./app
    container_name: php
    environment:
      - XDEBUG_CONFIG
      - PHP_XDEBUG_ENABLED
      - PHP_IDE_CONFIG
    volumes:
      - ./app:/app
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - "${SHARED}"

  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "${PUBLIC_DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: "${PASSWORD}"
    volumes:
      - /database:/var/lib/mysql

    networks:
      - "${SHARED}"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - "${SHARED}"
networks:
  shared:
    driver: bridge